param(
    # Release.yml passes the bare git tag (no leading "v") so the published tag,
    # zip filename, and embedded assembly version stay in sync. Local builds
    # leave this empty and get an auto-derived YYYY.M.D.N-XXXX dev stamp.
    [string]$Version = "",

    # Skip building the release/ zip. dist/ is still produced.
    [switch]$SkipZip
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

# Activate the repo's tracked git hooks (.githooks/) on first build in a clone.
# Idempotent; harmlessly no-ops outside a git checkout.
try { & git config --local core.hooksPath .githooks 2>$null } catch {}

$BuildDir     = Join-Path $PSScriptRoot "dist"
$ReleaseDir   = Join-Path $PSScriptRoot "release"
$ToolsStage   = Join-Path $PSScriptRoot "_tools_staging"
$StateFile    = Join-Path $PSScriptRoot ".local_build_state.json"

# --- Versioning ---
if ($Version) {
    if ($Version -notmatch '^\d{4}\.\d+\.\d+\.\d+(-[A-Fa-f0-9]{4})?$') {
        throw "Invalid -Version '$Version'. Expected YYYY.M.D.N (release) or YYYY.M.D.N-XXXX (dev)."
    }
    $FullVersion = $Version
} else {
    $Today = Get-Date -Format "yyyy.M.d"
    $BuildCount = 0
    if (Test-Path $StateFile) {
        $State = Get-Content $StateFile | ConvertFrom-Json
        if ($State.Date -eq $Today) { $BuildCount = [int]$State.Count + 1 }
    }
    $UID = [Guid]::NewGuid().ToString().Substring(0,4).ToUpper()
    $FullVersion = "$Today.$BuildCount-$UID"
    @{ Date = $Today; Count = $BuildCount } | ConvertTo-Json | Out-File $StateFile -Encoding utf8
}
# AssemblyVersion must be pure numeric (no -XXXX dev suffix)
$AsmVersion = ($FullVersion -split '-')[0]
Write-Host "Building Version: $FullVersion" -ForegroundColor Magenta

# --- Clean dist ---
if (Test-Path $BuildDir) { Remove-Item $BuildDir -Recurse -Force }
New-Item -ItemType Directory $BuildDir -Force | Out-Null
if (-not (Test-Path $ToolsStage)) { New-Item -ItemType Directory $ToolsStage -Force | Out-Null }

# --- Generate BuildInfo.cs (git short-SHA + build timestamp) ---
# Stamps the watchdog startup banner so the operator can correlate a
# running watchdog to a specific source revision without parsing the
# version number. Generated file lives under src/WKVRCProxy/Generated/
# and is gitignored -- each build overwrites it. Idempotent: if git is
# unavailable (release zip extracted, source-only build) fields fall
# back to "<unknown>" so the banner still renders cleanly.
$BuildInfoDir = Join-Path $PSScriptRoot "src/WKVRCProxy/Generated"
if (-not (Test-Path $BuildInfoDir)) { New-Item -ItemType Directory $BuildInfoDir -Force | Out-Null }
$BuildInfoPath = Join-Path $BuildInfoDir "BuildInfo.cs"
$gitSha = "<unknown>"
try {
    $resolved = & git rev-parse --short=12 HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $resolved) { $gitSha = $resolved.Trim() }
} catch { }
$gitDirty = ""
try {
    $statusOut = & git status --porcelain 2>$null
    if ($LASTEXITCODE -eq 0 -and $statusOut) { $gitDirty = "-dirty" }
} catch { }
$buildTime = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# IsDevBuild gates verbose [relay] req= logging in LocalRelayServer. The
# CI-produced release artifact is always treated as release mode (the only
# way to get a dev-mode CI build is to push a -XXXX-suffixed tag, which is
# vanishingly rare). CI's release.yml runs the changelog-promotion step
# before build.ps1, which leaves CHANGELOG.md modified -- a clean release
# tag would otherwise trip the dirty check and ship a verbose-logging
# binary. GITHUB_ACTIONS=true overrides the dirty check there.
#
# Local builds with a dirty tree DO get dev-mode -- they're prerelease
# experiments and the verbose log is the whole point.
if ($env:GITHUB_ACTIONS -eq 'true') {
    $isDev = $FullVersion -match '-'
} else {
    $isDev = ($FullVersion -match '-') -or ($gitDirty -ne "")
}
$isDevLiteral = if ($isDev) { "true" } else { "false" }

$buildInfoContent = @"
// Generated by build.ps1; do not edit by hand. Tracked in git with
// <unknown> placeholders; running build.ps1 overwrites with the real
// SHA + UTC timestamp. ``git checkout`` reverts to the placeholder.
namespace WKVRCProxy;
internal static class BuildInfo
{
    public const string GitSha = "$gitSha$gitDirty";
    public const string BuildTime = "$buildTime";
    public const bool IsDevBuild = $isDevLiteral;
}
"@
[System.IO.File]::WriteAllText($BuildInfoPath, $buildInfoContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "BuildInfo: GitSha=$gitSha$gitDirty BuildTime=$buildTime IsDevBuild=$isDevLiteral" -ForegroundColor DarkGray

# --- Bundled yt-dlp fallback (vanilla, for og-restore on missing backup) ---
$YtDlpFallback = Join-Path $ToolsStage "yt-dlp-og-fallback.exe"
$YtDlpVerFile  = Join-Path $ToolsStage "yt-dlp-og-fallback.version.txt"
Write-Host "`n--- Fetching bundled yt-dlp fallback ---" -ForegroundColor Cyan
$ApiHeaders = @{ "User-Agent" = "WKVRCProxy-build" }
$LatestYtDlp = (Invoke-RestMethod -Uri "https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest" -Headers $ApiHeaders).tag_name
$NeedRefresh = $true
if ((Test-Path $YtDlpFallback) -and (Test-Path $YtDlpVerFile)) {
    $current = (Get-Content $YtDlpVerFile -Raw -ErrorAction SilentlyContinue).Trim()
    if ($current -eq $LatestYtDlp) { $NeedRefresh = $false }
}
if ($NeedRefresh) {
    Invoke-WebRequest -Uri "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe" -OutFile $YtDlpFallback -UseBasicParsing
    $LatestYtDlp | Out-File $YtDlpVerFile -Encoding utf8 -NoNewline
    Write-Host "Fetched yt-dlp $LatestYtDlp." -ForegroundColor Green
} else {
    Write-Host "yt-dlp fallback up-to-date ($LatestYtDlp)." -ForegroundColor Green
}

# --- Publish .NET projects ---
# The four exes split into two publish profiles:
#   * Watchdog (WKVRCProxy.exe) — regular self-contained single-file with R2R.
#     Long-lived process; size doesn't matter as much; AOT audit pending.
#   * Updater + Uninstaller — AOT (csproj sets PublishAot/Trimmed/full).
#     Single native exe each; PublishSingleFile is incompatible with AOT
#     so the cmdline arg is split out into the watchdog-only PubArgs below.
#   * Wrapper (yt-dlp.exe in dist/tools/) — AOT, published separately
#     into dist/tools/ further down.
#
# Three of the four publishes (Updater, Uninstaller, YtDlp wrapper) run
# AOT, which means MSBuild's AOT target needs link.exe from MSVC. It looks
# up link.exe via vswhere.exe but vswhere isn't on PATH by default — VS
# Build Tools install it at %ProgramFiles(x86)%\Microsoft Visual Studio\
# Installer but the installer doesn't add the dir to PATH. Front-load the
# PATH munge once before any publish runs.
Write-Host "`n--- Publishing ---" -ForegroundColor Cyan
$ProgFilesX86 = [Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
$VsInstaller = Join-Path $ProgFilesX86 'Microsoft Visual Studio\Installer'
if (Test-Path (Join-Path $VsInstaller 'vswhere.exe')) {
    if ($env:PATH -notlike "*$VsInstaller*") { $env:PATH = "$VsInstaller;$env:PATH" }
} else {
    Write-Warning "vswhere.exe not found at $VsInstaller -- AOT link step may fail. Install Visual Studio Build Tools with the Desktop C++ workload."
}

# All four watchdog/Updater/Uninstaller/YtDlp now AOT-publish. The
# WatchdogPubArgs profile (single-file, R2R, JIT) is no longer used --
# AOT produces a single native exe inherently and PublishSingleFile is
# incompatible with PublishAot. Same $AotPubArgs for all of them.
$AotPubArgs      = @("-c","Release","-r","win-x64","--self-contained","true",
                     "/p:Version=$AsmVersion",
                     "-o",$BuildDir,"--nologo")
dotnet publish "src/WKVRCProxy/WKVRCProxy.csproj" @AotPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy publish failed" }
dotnet publish "src/WKVRCProxy.Updater/WKVRCProxy.Updater.csproj" @AotPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy.Updater publish failed" }
dotnet publish "src/WKVRCProxy.Uninstaller/WKVRCProxy.Uninstaller.csproj" @AotPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy.Uninstaller publish failed" }

# --- Stage tools/ subdir in dist ---
$BuildTools = Join-Path $BuildDir "tools"
New-Item -ItemType Directory $BuildTools -Force | Out-Null
Copy-Item $YtDlpFallback (Join-Path $BuildTools "yt-dlp-og-fallback.exe") -Force
Copy-Item $YtDlpVerFile  (Join-Path $BuildTools "yt-dlp-og-fallback.version.txt") -Force

# Publish the patched yt-dlp wrapper directly into dist/tools/. AssemblyName=yt-dlp
# in the project produces yt-dlp.exe; PatchManager copies this over VRChat's
# Tools/yt-dlp.exe at runtime.
#
# AOT publish for the wrapper specifically (csproj sets PublishAot/PublishTrimmed
# /TrimMode=full/InvariantGlobalization). Cuts the wrapper from ~79 MB to ~3 MB
# and removes JIT cold-start cost — VRChat invokes this binary per video player
# so size + startup directly impact in-game stutter on world load. The watchdog
# stays on regular self-contained .NET 10 (one-shot launch; size doesn't matter).
#
# Drops PublishSingleFile (AOT incompatible — produces a single native .exe
# inherently). vswhere.exe is already on PATH from the front-loaded munge
# at the top of the publish section.
$YtDlpPubArgs = @("-c","Release","-r","win-x64","--self-contained","true",
                  "/p:Version=$AsmVersion",
                  "-o",$BuildTools,"--nologo")
dotnet publish "src/WKVRCProxy.YtDlp/WKVRCProxy.YtDlp.csproj" @YtDlpPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy.YtDlp publish failed" }

# AOT publish leaves a yt-dlp.pdb (~14 MB) we don't need to ship — the .pdb
# strip below picks it up.

# --- Trim debug symbols we don't ship ---
Get-ChildItem $BuildDir -Filter "*.pdb" -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue

# --- Manifest (per-file SHA256 + size for the release-body File Integrity section) ---
# Tab-separated: <sha256>\t<size_bytes>\t<relative_path>. One file per line,
# sorted by path. Generate-ReleaseNotes.ps1 reads this to compose the inner-file
# hash table without needing to unzip the artifact.
if (-not $SkipZip) {
    if (-not (Test-Path $ReleaseDir)) { New-Item -ItemType Directory $ReleaseDir -Force | Out-Null }
    $ManifestPath = Join-Path $ReleaseDir "WKVRCProxy-v$FullVersion.manifest.tsv"
    $manifestLines = Get-ChildItem $BuildDir -Recurse -File |
        Sort-Object FullName |
        ForEach-Object {
            $relPath = $_.FullName.Substring($BuildDir.Length + 1) -replace '\\', '/'
            $sha = (Get-FileHash $_.FullName -Algorithm SHA256).Hash
            "$sha`t$($_.Length)`t$relPath"
        }
    [System.IO.File]::WriteAllLines($ManifestPath, [string[]]$manifestLines, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Manifest: $ManifestPath ($($manifestLines.Count) files)" -ForegroundColor Cyan
}

# --- Zip ---
if (-not $SkipZip) {
    $ZipPath = Join-Path $ReleaseDir "WKVRCProxy-v$FullVersion.zip"
    if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }
    Compress-Archive -Path (Join-Path $BuildDir "*") -DestinationPath $ZipPath
    Write-Host "`nRelease zip: $ZipPath" -ForegroundColor Green
}

Write-Host "`nBuild complete: v$FullVersion" -ForegroundColor Green
