param(
    # Release.yml passes the bare git tag (no leading "v") so the published tag,
    # zip filename, and embedded assembly version stay in sync. Local builds
    # leave this empty and get an auto-derived YYYY.M.D.N-XXXX dev stamp.
    [string]$Version = "",

    # Build the GitHub release zip + manifest. Local builds leave this off so
    # the repo root stays clean and only dist/ is refreshed.
    [switch]$Package,

    # Deprecated compatibility switch. Equivalent to leaving -Package off.
    [switch]$SkipZip,

    # Optional directory for package artifacts. Defaults to dist/ so all local
    # build output stays under one ignored tree.
    [string]$ArtifactsDir = ""
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

# Activate the repo's tracked git hooks (.githooks/) on first build in a clone.
# Idempotent; harmlessly no-ops outside a git checkout.
try { & git config --local core.hooksPath .githooks 2>$null } catch {}

$BuildDir     = Join-Path $PSScriptRoot "dist"
$ToolsStage   = Join-Path $PSScriptRoot "_tools_staging"
$StateFile    = Join-Path $PSScriptRoot ".local_build_state.json"
$CreatePackage = $Package -and -not $SkipZip

# --- Versioning ---
if ($Version) {
    # Accepted shapes:
    #   YYYY.M.D.N            release
    #   YYYY.M.D.N-XXXX       local dev rebuild (4 hex)
    #   YYYY.M.D.N-beta       prerelease (matches release.yml's '*-beta*'
    #                         detector which adds --prerelease on the
    #                         GitHub release)
    # For a second prerelease against the same numeric base, bump the
    # patch instead of numbering the suffix (e.g. 2026.5.22.1-beta).
    if ($Version -notmatch '^\d{4}\.\d+\.\d+\.\d+(-([A-Fa-f0-9]{4}|beta))?$') {
        throw "Invalid -Version '$Version'. Expected YYYY.M.D.N (release), YYYY.M.D.N-XXXX (dev), or YYYY.M.D.N-beta (prerelease)."
    }
    $FullVersion = $Version
} else {
    $Today = Get-Date -Format "yyyy.M.d"
    $BuildCount = 0
    if (Test-Path $StateFile) {
        $State = Get-Content $StateFile | ConvertFrom-Json
        if ($State.Date -eq $Today) { $BuildCount = [int]$State.Count + 1 }
    }
    $UID = [Guid]::NewGuid().ToString().Substring(0,4).ToUpper()
    $FullVersion = "$Today.$BuildCount-$UID"
    @{ Date = $Today; Count = $BuildCount } | ConvertTo-Json | Out-File $StateFile -Encoding utf8
}
# AssemblyVersion must be pure numeric (no -XXXX dev suffix)
$AsmVersion = ($FullVersion -split '-')[0]
Write-Host "Building Version: $FullVersion" -ForegroundColor Magenta

# --- Clean dist ---
if (Test-Path $BuildDir) { Remove-Item $BuildDir -Recurse -Force }
New-Item -ItemType Directory $BuildDir -Force | Out-Null
if (-not (Test-Path $ToolsStage)) { New-Item -ItemType Directory $ToolsStage -Force | Out-Null }

# --- Generate BuildInfo.cs (git short-SHA + build timestamp) ---
# Stamps the watchdog startup banner so the operator can correlate a
# running watchdog to a specific source revision without parsing the
# version number. Generated file lives under src/WKVRCProxy/Generated/
# and is gitignored -- each build overwrites it. Idempotent: if git is
# unavailable (release zip extracted, source-only build) fields fall
# back to "<unknown>" so the banner still renders cleanly.
$BuildInfoDir = Join-Path $PSScriptRoot "src/WKVRCProxy/Generated"
if (-not (Test-Path $BuildInfoDir)) { New-Item -ItemType Directory $BuildInfoDir -Force | Out-Null }
$BuildInfoPath = Join-Path $BuildInfoDir "BuildInfo.cs"
$gitSha = "<unknown>"
try {
    $resolved = & git rev-parse --short=12 HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $resolved) { $gitSha = $resolved.Trim() }
} catch { }
$gitDirty = ""
try {
    $statusOut = & git status --porcelain 2>$null
    if ($LASTEXITCODE -eq 0 -and $statusOut) { $gitDirty = "-dirty" }
} catch { }
$buildTime = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# IsDevBuild gates verbose [relay] req= logging in LocalRelayServer. The
# CI-produced release artifact is always treated as release mode (the only
# way to get a dev-mode CI build is to push a -XXXX-suffixed tag, which is
# vanishingly rare). CI's release.yml runs the changelog-promotion step
# before build.ps1, which leaves CHANGELOG.md modified -- a clean release
# tag would otherwise trip the dirty check and ship a verbose-logging
# binary. GITHUB_ACTIONS=true overrides the dirty check there.
#
# Local builds with a dirty tree DO get dev-mode -- they're prerelease
# experiments and the verbose log is the whole point.
if ($env:GITHUB_ACTIONS -eq 'true') {
    $isDev = $FullVersion -match '-'
} else {
    $isDev = ($FullVersion -match '-') -or ($gitDirty -ne "")
}
$isDevLiteral = if ($isDev) { "true" } else { "false" }

$buildInfoContent = @"
// Generated by build.ps1; do not edit by hand. Tracked in git with
// <unknown> placeholders; running build.ps1 overwrites with the real
// SHA + UTC timestamp. ``git checkout`` reverts to the placeholder.
namespace WKVRCProxy;
internal static class BuildInfo
{
    public const string GitSha = "$gitSha$gitDirty";
    public const string BuildTime = "$buildTime";
    public const bool IsDevBuild = $isDevLiteral;
}
"@
[System.IO.File]::WriteAllText($BuildInfoPath, $buildInfoContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "BuildInfo: GitSha=$gitSha$gitDirty BuildTime=$buildTime IsDevBuild=$isDevLiteral" -ForegroundColor DarkGray

# --- Bundled FFmpeg / FFprobe for local helper encoding ---
# WKVRCProxy helpers should not depend on a user-installed FFmpeg. Stage a
# static Windows build into dist/tools/ffmpeg.exe and dist/tools/ffprobe.exe,
# with the upstream checksum verified before extraction.
$FfmpegArchiveName = "ffmpeg-master-latest-win64-gpl.zip"
$FfmpegReleaseBase = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest"
$FfmpegArchive = Join-Path $ToolsStage $FfmpegArchiveName
$FfmpegShaFile = Join-Path $ToolsStage "$FfmpegArchiveName.sha256"
$FfmpegChecksums = Join-Path $ToolsStage "ffmpeg-checksums.sha256"
$FfmpegExtractRoot = Join-Path $ToolsStage "ffmpeg-win64-gpl"
Write-Host "`n--- Fetching bundled FFmpeg helper tools ---" -ForegroundColor Cyan
Invoke-WebRequest -Uri "$FfmpegReleaseBase/checksums.sha256" -OutFile $FfmpegChecksums -UseBasicParsing
$ChecksumLine = Get-Content $FfmpegChecksums |
    Where-Object { $_ -match "\s\*?$([regex]::Escape($FfmpegArchiveName))$" } |
    Select-Object -First 1
if (-not $ChecksumLine) {
    throw "Could not find checksum for $FfmpegArchiveName in BtbN checksums.sha256"
}
$ExpectedFfmpegSha = (($ChecksumLine -split "\s+")[0]).ToUpperInvariant()
$CurrentFfmpegSha = ""
if (Test-Path $FfmpegArchive) {
    $CurrentFfmpegSha = (Get-FileHash $FfmpegArchive -Algorithm SHA256).Hash.ToUpperInvariant()
}
$FfmpegArchiveChanged = $false
if ($CurrentFfmpegSha -ne $ExpectedFfmpegSha) {
    Invoke-WebRequest -Uri "$FfmpegReleaseBase/$FfmpegArchiveName" -OutFile $FfmpegArchive -UseBasicParsing
    $CurrentFfmpegSha = (Get-FileHash $FfmpegArchive -Algorithm SHA256).Hash.ToUpperInvariant()
    $FfmpegArchiveChanged = $true
}
if ($CurrentFfmpegSha -ne $ExpectedFfmpegSha) {
    throw "FFmpeg checksum mismatch. Expected $ExpectedFfmpegSha but got $CurrentFfmpegSha"
}
$ExpectedFfmpegSha | Out-File $FfmpegShaFile -Encoding utf8 -NoNewline

$ExistingFfmpeg = Get-ChildItem $FfmpegExtractRoot -Recurse -Filter "ffmpeg.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
$ExistingFfprobe = Get-ChildItem $FfmpegExtractRoot -Recurse -Filter "ffprobe.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($FfmpegArchiveChanged -or -not $ExistingFfmpeg -or -not $ExistingFfprobe) {
    if (Test-Path $FfmpegExtractRoot) { Remove-Item $FfmpegExtractRoot -Recurse -Force }
    New-Item -ItemType Directory $FfmpegExtractRoot -Force | Out-Null
    Expand-Archive -Path $FfmpegArchive -DestinationPath $FfmpegExtractRoot -Force
}
$FfmpegExe = Get-ChildItem $FfmpegExtractRoot -Recurse -Filter "ffmpeg.exe" | Select-Object -First 1
$FfprobeExe = Get-ChildItem $FfmpegExtractRoot -Recurse -Filter "ffprobe.exe" | Select-Object -First 1
if (-not $FfmpegExe -or -not $FfprobeExe) {
    throw "Extracted FFmpeg archive did not contain ffmpeg.exe and ffprobe.exe"
}
Write-Host "FFmpeg helper tools ready ($($ExpectedFfmpegSha.Substring(0,12)))." -ForegroundColor Green

# --- Publish .NET projects ---
# The four exes split into two publish profiles:
#   * Watchdog (WKVRCProxy.exe) — regular self-contained single-file with R2R.
#     Long-lived process; size doesn't matter as much; AOT audit pending.
#   * Updater + Uninstaller — AOT (csproj sets PublishAot/Trimmed/full).
#     Single native exe each; PublishSingleFile is incompatible with AOT
#     so the cmdline arg is split out into the watchdog-only PubArgs below.
#   * Wrapper (yt-dlp.exe in dist/tools/) — AOT, published separately
#     into dist/tools/ further down.
#
# Three of the four publishes (Updater, Uninstaller, YtDlp wrapper) run
# AOT, which means MSBuild's AOT target needs link.exe from MSVC. It looks
# up link.exe via vswhere.exe but vswhere isn't on PATH by default — VS
# Build Tools install it at %ProgramFiles(x86)%\Microsoft Visual Studio\
# Installer but the installer doesn't add the dir to PATH. Front-load the
# PATH munge once before any publish runs.
Write-Host "`n--- Publishing ---" -ForegroundColor Cyan
$ProgFilesX86 = [Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
$VsInstaller = Join-Path $ProgFilesX86 'Microsoft Visual Studio\Installer'
if (Test-Path (Join-Path $VsInstaller 'vswhere.exe')) {
    if ($env:PATH -notlike "*$VsInstaller*") { $env:PATH = "$VsInstaller;$env:PATH" }
} else {
    Write-Warning "vswhere.exe not found at $VsInstaller -- AOT link step may fail. Install Visual Studio Build Tools with the Desktop C++ workload."
}

# All four watchdog/Updater/Uninstaller/YtDlp now AOT-publish. The
# WatchdogPubArgs profile (single-file, R2R, JIT) is no longer used --
# AOT produces a single native exe inherently and PublishSingleFile is
# incompatible with PublishAot. Same $AotPubArgs for all of them.
$AotPubArgs      = @("-c","Release","-r","win-x64","--self-contained","true",
                     "/p:Version=$AsmVersion",
                     "-o",$BuildDir,"--nologo")
dotnet publish "src/WKVRCProxy/WKVRCProxy.csproj" @AotPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy publish failed" }
dotnet publish "src/WKVRCProxy.Updater/WKVRCProxy.Updater.csproj" @AotPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy.Updater publish failed" }
dotnet publish "src/WKVRCProxy.Uninstaller/WKVRCProxy.Uninstaller.csproj" @AotPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy.Uninstaller publish failed" }

# --- Stage tools/ subdir in dist ---
$BuildTools = Join-Path $BuildDir "tools"
New-Item -ItemType Directory $BuildTools -Force | Out-Null
Copy-Item $FfmpegExe.FullName (Join-Path $BuildTools "ffmpeg.exe") -Force
Copy-Item $FfprobeExe.FullName (Join-Path $BuildTools "ffprobe.exe") -Force
$FfmpegNoticeDir = Join-Path $BuildTools "ffmpeg-notices"
New-Item -ItemType Directory $FfmpegNoticeDir -Force | Out-Null
Get-ChildItem $FfmpegExtractRoot -Recurse -File |
    Where-Object { $_.Name -match '^(LICENSE|COPYING|README|VERSION|NOTICE)' } |
    ForEach-Object { Copy-Item $_.FullName (Join-Path $FfmpegNoticeDir $_.Name) -Force }

# Publish the patched yt-dlp wrapper directly into dist/tools/. AssemblyName=yt-dlp
# in the project produces yt-dlp.exe; PatchManager copies this over VRChat's
# Tools/yt-dlp.exe at runtime.
#
# AOT publish for the wrapper specifically (csproj sets PublishAot/PublishTrimmed
# /TrimMode=full/InvariantGlobalization). Cuts the wrapper from ~79 MB to ~3 MB
# and removes JIT cold-start cost — VRChat invokes this binary per video player
# so size + startup directly impact in-game stutter on world load. The watchdog
# stays on regular self-contained .NET 10 (one-shot launch; size doesn't matter).
#
# Drops PublishSingleFile (AOT incompatible — produces a single native .exe
# inherently). vswhere.exe is already on PATH from the front-loaded munge
# at the top of the publish section.
$YtDlpPubArgs = @("-c","Release","-r","win-x64","--self-contained","true",
                  "/p:Version=$AsmVersion",
                  "-o",$BuildTools,"--nologo")
dotnet publish "src/WKVRCProxy.YtDlp/WKVRCProxy.YtDlp.csproj" @YtDlpPubArgs
if ($LASTEXITCODE -ne 0) { throw "WKVRCProxy.YtDlp publish failed" }

# AOT publish leaves a yt-dlp.pdb (~14 MB) we don't need to ship — the .pdb
# strip below picks it up.

# --- Stage data/ subdir in dist (known wrapper hashes list) ---
# Ships `data/known_wrapper_hashes.txt` alongside WKVRCProxy.exe so the
# watchdog can identify older WKVRCProxy wrapper binaries that pre-date the
# current install. The file is repo-tracked and maintained by the release
# workflow (one SHA appended per published release). Dev builds carry
# whatever state the working tree has and rely on the PE-metadata + embedded
# marker signals for self-identification.
$BuildData = Join-Path $BuildDir "data"
New-Item -ItemType Directory $BuildData -Force | Out-Null
$KnownHashesSrc = Join-Path $PSScriptRoot "data/known_wrapper_hashes.txt"
if (Test-Path $KnownHashesSrc) {
    Copy-Item $KnownHashesSrc (Join-Path $BuildData "known_wrapper_hashes.txt") -Force
} else {
    Write-Warning "data/known_wrapper_hashes.txt missing from repo -- shipping empty list"
    "" | Out-File (Join-Path $BuildData "known_wrapper_hashes.txt") -Encoding utf8 -NoNewline
}

# --- Trim debug symbols we don't ship ---
Get-ChildItem $BuildDir -Filter "*.pdb" -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue

# --- Package artifacts for GitHub releases ---
# Local builds stop at dist/. GitHub release builds pass -Package, which writes
# the zip + manifest into dist/ (or -ArtifactsDir) without creating a repo-root
# release/ directory.
if ($CreatePackage) {
    $ArtifactRoot = if ($ArtifactsDir) { $ArtifactsDir } else { $BuildDir }
    if (-not [System.IO.Path]::IsPathRooted($ArtifactRoot)) {
        $ArtifactRoot = Join-Path $PSScriptRoot $ArtifactRoot
    }
    if (-not (Test-Path $ArtifactRoot)) { New-Item -ItemType Directory $ArtifactRoot -Force | Out-Null }

    $ManifestPath = Join-Path $ArtifactRoot "WKVRCProxy-v$FullVersion.manifest.tsv"
    $ZipPath = Join-Path $ArtifactRoot "WKVRCProxy-v$FullVersion.zip"
    if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }

    # Manifest is tab-separated: <sha256>\t<size_bytes>\t<relative_path>.
    # Generate-ReleaseNotes.ps1 reads this to compose the inner-file hash table
    # without needing to unzip the artifact. Capture package inputs before
    # writing the manifest so the manifest itself never appears in the zip.
    $PackageFiles = Get-ChildItem $BuildDir -Recurse -File |
        Sort-Object FullName
    $manifestLines = $PackageFiles | ForEach-Object {
        $relPath = $_.FullName.Substring($BuildDir.Length + 1) -replace '\\', '/'
        $sha = (Get-FileHash $_.FullName -Algorithm SHA256).Hash
        "$sha`t$($_.Length)`t$relPath"
    }
    $PackageInputs = Get-ChildItem $BuildDir -Force | ForEach-Object { $_.FullName }
    [System.IO.File]::WriteAllLines($ManifestPath, [string[]]$manifestLines, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Manifest: $ManifestPath ($($manifestLines.Count) files)" -ForegroundColor Cyan

    Compress-Archive -Path $PackageInputs -DestinationPath $ZipPath
    Write-Host "`nRelease zip: $ZipPath" -ForegroundColor Green
}

Write-Host "`nBuild complete: v$FullVersion" -ForegroundColor Green
