<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VrcResolver.Uninstaller</RootNamespace>
    <AssemblyName>vrcresolver.Uninstaller</AssemblyName>
    <Company>RealWhyKnot</Company>
    <Product>VRCResolver</Product>
    <AssemblyTitle>VRCResolver uninstaller</AssemblyTitle>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VrcResolver.Shared\VrcResolver.Shared.csproj" />
  </ItemGroup>

</Project>
