<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VrcResolver.YtDlp</RootNamespace>
    <AssemblyName>yt-dlp</AssemblyName>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <InvariantGlobalization>true</InvariantGlobalization>

    <Company>RealWhyKnot</Company>
    <Product>VRCResolver</Product>
    <AssemblyTitle>VRCResolver yt-dlp wrapper</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VrcResolver.Shared\VrcResolver.Shared.csproj" />
  </ItemGroup>

</Project>
